routes/web.php
<?php

use App\Http\Controllers\Parking\FinishParkingController;
use App\Http\Controllers\Parking\InitParkingController;
use App\Http\Controllers\Parking\ParkingIndexController;
use App\Http\Controllers\RecordController;
use App\Http\Controllers\Stay\IndexStayController;
use App\Http\Controllers\Stay\ReportStayController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\datatables\RecordDatatable;
use App\Http\Controllers\datatables\StayDatatable;
use App\Http\Controllers\datatables\TypeDatatable;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ParkingIndexController::class, 'index'])->name('index');

Route::post('parking/init', [InitParkingController::class, 'initParking'])->name('parking.initParking');

Route::post('parking/finish', [FinishParkingController::class, 'finishParking'])->name('parking.finishParking');

Route::get('stay', [IndexStayController::class, 'index'])->name('stay.index');

Route::post('stay/xls', [ReportStayController::class, 'downloadXls'])->name('stay.xls');

Route::post('stay/pdf', [ReportStayController::class, 'downloadPdf'])->name('stay.pdf');

Route::resource('type', TypeController::class)->except(['show']);

Route::resource('record', RecordController::class)->except(['show']);

Route::prefix('datatable')->group(function () {
    Route::get('type', [TypeDatatable::class, 'typeDatatable'])->name('datatable.type');
    Route::get('record', [RecordDatatable::class, 'recordDatatable'])->name('datatable.record');
    Route::get('stay', [StayDatatable::class, 'stayDatatable'])->name('datatable.stay');
});

resources/views/401.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>404 Error - SB Admin</title>
        <link href="css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-4">
                                    <h1 class="display-1">401</h1>
                                    <p class="lead">Unauthorized</p>
                                    <p>Access to this resource is denied.</p>
                                    <a href="index.html">
                                        <i class="fas fa-arrow-left me-1"></i>
                                        Return to Dashboard
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutError_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

resources/views/404.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>404 Error - SB Admin</title>
        <link href="css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-4">
                                    <img class="mb-4 img-error" src="assets/img/error-404-monochrome.svg" />
                                    <p class="lead">This requested URL was not found on this server.</p>
                                    <a href="index.html">
                                        <i class="fas fa-arrow-left me-1"></i>
                                        Return to Dashboard
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutError_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

resources/views/500.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>404 Error - SB Admin</title>
        <link href="css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-4">
                                    <h1 class="display-1">500</h1>
                                    <p class="lead">Internal Server Error</p>
                                    <a href="index.html">
                                        <i class="fas fa-arrow-left me-1"></i>
                                        Return to Dashboard
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutError_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

resources/views/index.blade.php
@extends('layout')
@section('styles')
<style type="text/css">
.slot {
	height: 6rem;
	position: relative;
	cursor: pointer;
}
.slot-num {
	position: absolute;
	top: 0;
	left: 0;
}
</style>
@endsection
@section('content')
<h1 class="mt-4">Estacionamiento</h1>
<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item active">Estacionamiento</li>
</ol>

<div class="row parking pb-3">
	@foreach($parkings as $parking)
	<div class="col-6 col-md-4 col-lg-3 text-center p-2 slot border {{ $parking->plate?'bg-primary':'' }}" data-slot="{{ $parking->slot }}" data-bs-toggle="modal" data-bs-target="#{{ $parking->plate?'modal2':'exampleModal'}}">
		<strong class="fs-5 slot-num p-1">{{ $parking->slot }}</strong>
		@if($parking->plate)
		<strong class="p-4 fs-4">{{ $parking->plate }}</strong>
		@endif
	</div>
	@endforeach
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel"></h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form method="POST" action="{{ route('parking.initParking') }}">
					@csrf
					<input type="hidden" id="parkigSlotId" name="slot">
					<div class="mb-3">
						<label for="placa" class="form-label">Número de placa</label>
						<input type="text" class="form-control" id="placa" name="placa">
					</div>
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
					<button type="submit" class="btn btn-primary">Confirmar</button>
				</form>
			</div>
			
		</div>
	</div>
</div>


<div class="modal fade" id="modal2" tabindex="-1" aria-labelledby="modal2Label" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="modal2Label">Modal title</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form id="formCobrar" method="POST" action="{{ route('parking.finishParking') }}">
					@csrf
					<input type="hidden" id="parkigSlotId2" name="slot">
					<div class="mb-3">
						<p class="fs-5">¿Deseas cobrar el tiempo de estacionamiento?</p>
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
						<button type="submit" class="btn btn-primary">Confirmar</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@if($stay = Session::get('cobrar'))
<div class="modal fade" id="cobrarModal" tabindex="-1" aria-labelledby="cobrarModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cobrarModalLabel">Cobrar</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div>
					<strong>Tipo: </strong>{{$stay->type}}
				</div>
				<div>
					<strong>Minutos: </strong>{{$stay->out->diffInMinutes($stay->in)}}
				</div>
				<div>
					<strong>Total a cobrar: </strong>{{$stay->cost}}
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success" data-bs-dismiss="modal">Aceptar</button>
			</div>
		</div>
	</div>
</div>
@endif

@endsection
@section('scripts')
<script type="text/javascript">
	document.getElementById('exampleModal').addEventListener('show.bs.modal', function (event) {
		var slot = event.relatedTarget.dataset.slot;
		document.getElementById('exampleModalLabel').textContent = 'Slot ' + slot;
		document.getElementById('parkigSlotId').value = slot;
	});
	document.getElementById('modal2').addEventListener('show.bs.modal', function (event) {
		var slot = event.relatedTarget.dataset.slot;
		document.getElementById('modal2Label').textContent = 'Slot ' + slot;
		document.getElementById('parkigSlotId2').value = slot;
	});
	@if(Session::get('cobrar'))
	var myModal = new bootstrap.Modal(document.getElementById("cobrarModal"), {});
	document.onreadystatechange = function () {
		myModal.show();
	};
	@endif
</script>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Control de estacionamiento" />
    <meta name="author" content="Miguel Jimenez" />
    <title>Estacionamiento</title>
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet" />
    @yield('styles')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    @yield('head-scripts')
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="#">Estacionamiento</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link" href="{{ route('index') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                            Inicio
                        </a>
                        <a class="nav-link" href="{{ route('record.index') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Registro
                        </a>
                        <a class="nav-link" href="{{ route('type.index') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-cubes"></i></div>
                            Tipo
                        </a>
                        <a class="nav-link" href="{{ route('stay.index') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Historico
                        </a>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                 @yield('content')
             </div>
         </main>
         <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Estacionamiento 2021</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="{{ asset('js/scripts.js') }}"></script>
@yield('scripts')
</body>
</html>