routes/web.php
<?php

use App\Http\Controllers\Parking\FinishParkingController;
use App\Http\Controllers\Parking\InitParkingController;
use App\Http\Controllers\Parking\ParkingIndexController;
use App\Http\Controllers\RecordController;
use App\Http\Controllers\Stay\IndexStayController;
use App\Http\Controllers\Stay\ReportStayController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\datatables\RecordDatatable;
use App\Http\Controllers\datatables\StayDatatable;
use App\Http\Controllers\datatables\TypeDatatable;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ParkingIndexController::class, 'index'])->name('index');

Route::post('parking/init', [InitParkingController::class, 'initParking'])->name('parking.initParking');

Route::post('parking/finish', [FinishParkingController::class, 'finishParking'])->name('parking.finishParking');

Route::get('stay', [IndexStayController::class, 'index'])->name('stay.index');

Route::post('stay/xls', [ReportStayController::class, 'downloadXls'])->name('stay.xls');

Route::post('stay/pdf', [ReportStayController::class, 'downloadPdf'])->name('stay.pdf');

Route::resource('type', TypeController::class)->except(['show']);

Route::resource('record', RecordController::class)->except(['show']);

Route::prefix('datatable')->group(function () {
    Route::get('type', [TypeDatatable::class, 'typeDatatable'])->name('datatable.type');
    Route::get('record', [RecordDatatable::class, 'recordDatatable'])->name('datatable.record');
    Route::get('stay', [StayDatatable::class, 'stayDatatable'])->name('datatable.stay');
});

app/Models/Record.php
<?php

namespace App\Models;

use App\Models\Type;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Record extends Model
{
    use HasFactory;

    public function type() {
        return $this->belongsTo(Type::class);
    }

}

app/Http/Controllers/RecordController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Record\StoreRecordRequest;
use App\Http\Requests\Record\UpdateRecordRequest;
use App\Models\Record;
use App\Models\Type;
use Illuminate\Http\Request;

class RecordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('record.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = Type::where('default', false)->get();
        return view('record.create', compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRecordRequest $request)
    {
        $type = Type::where('id', $request->tipo)->where('default', false)->first();
        if ($type) {
            $record = new Record();
            $record->plate = $request->placa;
            $record->type_id = $type->id;
            $record->save();    
        }
        return view('record.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Record  $record
     * @return \Illuminate\Http\Response
     */
    public function show(Record $record)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Record  $record
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $record = Record::with('type')->where('id', $id)->firstOrFail();
        $types = Type::where('default', false)->get();
        return view('record.edit', compact('record', 'types'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Record  $record
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRecordRequest $request, Record $record)
    {
        $type = Type::where('id', $request->tipo)->where('default', false)->first();
        if ($type) {
            $record->plate = $request->placa;
            $record->type_id = $type->id;
            $record->save();
        }
        return redirect()->route('record.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Record  $record
     * @return \Illuminate\Http\Response
     */
    public function destroy(Record $record)
    {
        $record->delete();
        return redirect()->route('record.index');
    }
}

resources/views/record/create.blade.php
@extends('layout')
@section('content')
<h1 class="mt-4">Registro</h1>
<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item active">Registro</li>
</ol>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-plus-circle"></i>
        Nuevo
    </div>
    <div class="card-body">
        <form method="POST" action="{{ route('record.store') }}">
            @csrf
            <div class="mb-3">
                <label for="placa" class="form-label">Placa</label>
                <input type="text" class="form-control" id="placa" name="placa" value="{{ old('placa') }}" required>
                {!! $errors->first('placa', '<span class="text-danger">:message</span>') !!}
            </div>
            <div class="mb-3">
                <label for="cost" class="form-label">Tipo</label>
                <select class="form-select" name="tipo" required>
                    @foreach($types as $type)
                    <option value="{{ $type->id }}" {{ $loop->first?'selected':'' }}>{{ $type->type }}</option>
                    @endforeach
              </select>
              {!! $errors->first('costo', '<span class="text-danger">:message</span>') !!}
          </div>
          <button type="submit" class="btn btn-primary">Enviar</button>
          <a href="{{ route('type.index') }}" class="btn btn-danger">Cancelar</a>
      </form>
  </div>
</div>
@endsection

resources/views/record/edit.blade.php
@extends('layout')
@section('content')
<h1 class="mt-4">Registro</h1>
<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item active">Registro</li>
</ol>
<div class="card mb-4">
    <div class="card-header">
        <i class="far fa-edit me-1"></i>
        Editar
    </div>
    <div class="card-body">
        <form method="POST" action="{{ route('record.update', $record->id) }}">
            @csrf
            @method('PUT')
            <div class="mb-3">
                <label for="placa" class="form-label">Placa</label>
                <input type="text" class="form-control" id="placa" name="placa" value="{{ $record->plate }}" required>
                {!! $errors->first('placa', '<span class="text-danger">:message</span>') !!}
            </div>
            <div class="mb-3">
                <label for="cost" class="form-label">Tipo</label>
                <select class="form-select" name="tipo" required>
                    @foreach($types as $type)
                    <option value="{{ $type->id }}" {{ $record->type->id == $type->id?'selected':'' }}>{{ $type->type }}</option>
                    @endforeach
              </select>
              {!! $errors->first('costo', '<span class="text-danger">:message</span>') !!}
          </div>
          <button type="submit" class="btn btn-primary">Editar</button>
          <a href="{{ route('record.index') }}" class="btn btn-danger">Cancelar</a>
      </form>
  </div>
</div>
@endsection

resources/views/record/index.blade.php
@extends('layout')
@section('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
@endsection
@section('content')
<h1 class="mt-4">Registro</h1>
<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item active">Registro</li>
</ol>
<a class="btn btn-primary mb-3" href="{{ route('record.create') }}">
    <i class="fas fa-plus-circle"></i>
    Nuevo
</a>
<div class="card mb-4">
    <div class="card-body">
        <table id="record-datatable" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Placa</th>
                    <th>Tipo</th>
                    <th>Acción</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
<form id="formEliminar" method="POST">
    @method('DELETE')
    @csrf
    <input type="hidden" id="id">
</form>
@endsection
@section('scripts')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.min.js"></script>
<script>
    $(document).ready(function() {
        var table = $('#record-datatable').DataTable({
            processing: true,
            serverSide: true,
            language: {
                "sProcessing":"Procesando...",
                "sLengthMenu":"Mostrar _MENU_ registros",
                "sZeroRecords":"No se encontraron resultados",
                "sEmptyTable":"Ningún dato disponible en esta tabla",
                "sInfo":"Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":"Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":"(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":"",
                "sSearch":"Buscar:",
                "sUrl":"",
                "sInfoThousands":",",
                "sLoadingRecords":"Cargando...",
                "oPaginate": {
                    "sFirst":"Primero",
                    "sLast":"Último",
                    "sNext":"Siguiente",
                    "sPrevious":"Anterior"
                },
                "oAria": {
                    "sSortAscending":": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending":": Activar para ordenar la columna de manera descendente"
                }
            },
            ajax: '{!! route("datatable.record") !!}',
            columns: [
            {data: 'plate', name: 'plate'},
            {data: 'type.type', name: 'type.type'},
            {defaultContent: "<table><tr><td><button class='editar btn btn-warning'><i class='far fa-edit' aria-hidden='true'></i></button></td><td><button class='eliminar btn btn-danger text-dark'><i class='far fa-trash-alt' aria-hidden='true'></i></button></td></tr></table>", orderable: false, searchable: false}
            ]
        });

        $("#record-datatable tbody").on("click", "button.editar", function(){
            var row = table.row($(this).parents("tr")).data();
            location.href = "{{ route('record.index') }}" + "/" + row['id'] + "/edit";
        });
        $("#record-datatable tbody").on("click", "button.eliminar", function(){
            if(confirm("Realmente desea eliminar éste registro")){
                var row = table.row($(this).parents("tr")).data();
                $("#id").val(row["id"]);
                $("#formEliminar").attr("action","{{ route('record.index') }}"+"/"+row["id"]);
                $("#formEliminar").submit();
            }
        });

    });
</script>


@endsection