routes/web.php
<?php

use App\Http\Controllers\Parking\FinishParkingController;
use App\Http\Controllers\Parking\InitParkingController;
use App\Http\Controllers\Parking\ParkingIndexController;
use App\Http\Controllers\RecordController;
use App\Http\Controllers\Stay\IndexStayController;
use App\Http\Controllers\Stay\ReportStayController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\datatables\RecordDatatable;
use App\Http\Controllers\datatables\StayDatatable;
use App\Http\Controllers\datatables\TypeDatatable;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ParkingIndexController::class, 'index'])->name('index');

Route::post('parking/init', [InitParkingController::class, 'initParking'])->name('parking.initParking');

Route::post('parking/finish', [FinishParkingController::class, 'finishParking'])->name('parking.finishParking');

Route::get('stay', [IndexStayController::class, 'index'])->name('stay.index');

Route::post('stay/xls', [ReportStayController::class, 'downloadXls'])->name('stay.xls');

Route::post('stay/pdf', [ReportStayController::class, 'downloadPdf'])->name('stay.pdf');

Route::resource('type', TypeController::class)->except(['show']);

Route::resource('record', RecordController::class)->except(['show']);

Route::prefix('datatable')->group(function () {
    Route::get('type', [TypeDatatable::class, 'typeDatatable'])->name('datatable.type');
    Route::get('record', [RecordDatatable::class, 'recordDatatable'])->name('datatable.record');
    Route::get('stay', [StayDatatable::class, 'stayDatatable'])->name('datatable.stay');
});

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Type\StoreTypeRequest;
use App\Models\Type;
use Illuminate\Http\Request;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('type.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTypeRequest $request)
    {
        $type = new Type();
        $type->type = $request->tipo;
        $type->cost = $request->costo;
        $type->save();
        return view('type.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function show(Type $type)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function edit(Type $type)
    {
        return view('type.edit', compact('type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTypeRequest $request, Type $type)
    {
        $type->type = $request->tipo;
        $type->cost = $request->costo;
        $type->save();
        return redirect()->route('type.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function destroy(Type $type)
    {
        if (!$type->default) {
            $type->delete();
        }
        return redirect()->route('type.index');
    }
}

resources/views/type/create.blade.php
@extends('layout')
@section('content')
<h1 class="mt-4">Tipo</h1>
<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item active">Tipo</li>
</ol>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-plus-circle"></i>
        Nuevo
    </div>
    <div class="card-body">
        <form method="POST" action="{{ route('type.store') }}">
            @csrf
            <div class="mb-3">
                <label for="type" class="form-label">Tipo</label>
                <input type="text" class="form-control" id="type" name="tipo" value="{{ old('tipo') }}" required>
                {!! $errors->first('tipo', '<span class="text-danger">:message</span>') !!}
            </div>
            <div class="mb-3">
                <label for="cost" class="form-label">Costo</label>
                <input type="number" class="form-control" id="cost" min="0" step=".01" name="costo" value="{{ old('costo') }}" required>
                {!! $errors->first('costo', '<span class="text-danger">:message</span>') !!}
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
            <a href="{{ route('type.index') }}" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
@endsection

resources/views/type/edit.blade.php
@extends('layout')
@section('content')
<h1 class="mt-4">Tipo</h1>
<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item active">Tipo</li>
</ol>
<div class="card mb-4">
    <div class="card-header">
        <i class="far fa-edit me-1"></i>
        Editar
    </div>
    <div class="card-body">
        <form method="POST" action="{{ route('type.update', $type->id) }}">
            @csrf
            @method('PUT')
            <div class="mb-3">
                <label for="type" class="form-label">Tipo</label>
                <input type="text" class="form-control" id="type" name="tipo" value="{{ $type->type }}" {{ $type->default ? 'disabled':'' }} required>
                {!! $errors->first('tipo', '<span class="text-danger">:message</span>') !!}
            </div>
            <div class="mb-3">
                <label for="cost" class="form-label">Costo</label>
                <input type="number" class="form-control" id="cost" min="0" step=".01" name="costo" value="{{ $type->cost }}" required>
                {!! $errors->first('costo', '<span class="text-danger">:message</span>') !!}
            </div>
            <button type="submit" class="btn btn-primary">Editar</button>
            <a href="{{ route('type.index') }}" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
@endsection

resources/views/type/index.blade.php
@extends('layout')
@section('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
@endsection
@section('content')
<h1 class="mt-4">Tipo</h1>
<ol class="breadcrumb mb-4">
	<li class="breadcrumb-item active">Tipo</li>
</ol>
<a class="btn btn-primary mb-3" href="{{ route('type.create') }}">
    <i class="fas fa-plus-circle"></i>
    Nuevo
</a>
<div class="card mb-4">
    <div class="card-body">
        <table id="type-datatable" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Tipo</th>
                    <th>Cuota</th>
                    <th>Acción</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
<form id="formEliminar" method="POST">
    @method('DELETE')
    @csrf
    <input type="hidden" id="id">
</form>
@endsection
@section('scripts')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.min.js"></script>
<script>
    $(document).ready(function() {
        var table = $('#type-datatable').DataTable({
            processing: true,
            serverSide: true,
            language: {
                "sProcessing":"Procesando...",
                "sLengthMenu":"Mostrar _MENU_ registros",
                "sZeroRecords":"No se encontraron resultados",
                "sEmptyTable":"Ningún dato disponible en esta tabla",
                "sInfo":"Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":"Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":"(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":"",
                "sSearch":"Buscar:",
                "sUrl":"",
                "sInfoThousands":",",
                "sLoadingRecords":"Cargando...",
                "oPaginate": {
                    "sFirst":"Primero",
                    "sLast":"Último",
                    "sNext":"Siguiente",
                    "sPrevious":"Anterior"
                },
                "oAria": {
                    "sSortAscending":": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending":": Activar para ordenar la columna de manera descendente"
                }
            },
            ajax: '{!! route("datatable.type") !!}',
            columns: [
            {data: 'type', name: 'type'},
            {data: 'cost', name: 'cost'},
            {defaultContent: "<table><tr><td><button class='editar btn btn-warning'><i class='far fa-edit' aria-hidden='true'></i></button></td><td><button class='eliminar btn btn-danger text-dark'><i class='far fa-trash-alt' aria-hidden='true'></i></button></td></tr></table>", orderable: false, searchable: false}
            ]
        });

        $("#type-datatable tbody").on("click", "button.editar", function(){
            var row = table.row($(this).parents("tr")).data();
            location.href = "{{ route('type.index') }}" + "/" + row['id'] + "/edit";
        });
        $("#type-datatable tbody").on("click", "button.eliminar", function(){
            if(confirm("Realmente desea eliminar éste registro")){
                var row = table.row($(this).parents("tr")).data();
                $("#id").val(row["id"]);
                $("#formEliminar").attr("action","{{ route('type.index') }}"+"/"+row["id"]);
                $("#formEliminar").submit();
            }
        });

    });
</script>


@endsection